export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_CHECK_LOGIN_RELOAD = "AUTH_CHECK_LOGIN_RELOAD"
export const AUTH_REGISTER = "AUTH_REGISTER"

export const AUTH_GET_CURRENT_USER = "AUTH_GET_CURRENT_USER"
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN"