export const CART_GET_CART = "CART_GET_CART"
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT"
export const CART_DELETE_PRODUCT = "CART_DELETE_PRODUCT"
export const CART_EDIT_NUMBER_PRODUCT = "CART_EDIT_NUMBER_PRODUCT"
